### ISSUE TITLE
无法运行呀

### ISSUE THREAD

**Issue by abattle** [Steve-xmh/scratch-judge#8]
(base) :~ mac$ scj -h
/usr/local/bin/scj: line 1: use strict: command not found
/usr/local/bin/scj: line 2: syntax error near unexpected token `('
/usr/local/bin/scj: line 2: `const cli = require('cli')'
(base) :~ mac$ scj src/index.js -p test/test.sb3 -d test/ -o 3
/usr/local/bin/scj: line 1: use strict: command not found
/usr/local/bin/scj: line 2: syntax error near unexpected token `('
/usr/local/bin/scj: line 2: `const cli = require('cli')'
(base) :~ mac$

**Comment by Steve-xmh** [comment]
由于没有添加 `#!/bin/node` 让 linux 系系统选择正确的执行程序，请改用 `node ./src/index.js` 运行脚本
